In [8]:
using BenchmarkTools
using DataFrames
using DelimitedFiles
using CSV
using JSON


In [10]:
using Statistics
using StatsBase
using RDatasets
using Plots
using StatsPlots
using KernelDensity
using Distributions
using LinearAlgebra
using HypothesisTests
using PyCall
using MLBase

In [3]:
C = CSV.read("Cook_County_Assessor_s_Residential_Property_Characteristics.csv", DataFrame);

In [5]:
@show typeof(C)
C[1:10,:]

typeof(C) = DataFrame


10×82 DataFrame
 Row │ PIN            Property Class  Tax Year  Neighborhood Code  Land Square ⋯
     │ Int64          Int64           Int64     Int64              Int64       ⋯
─────┼──────────────────────────────────────────────────────────────────────────
   1 │ 1011000040000             212      2018                 12              ⋯
   2 │ 1011000050000             205      2018                 12
   3 │ 1011000060000             212      2018                 12
   4 │ 1011000090000             212      2018                 12
   5 │ 1011000170000             205      2018                 12              ⋯
   6 │ 1011000180000             205      2018                 12
   7 │ 1011000190000             202      2018                 12
   8 │ 1011000200000             211      2018                 12
   9 │ 1011000230000             205      2018                 12              ⋯
  10 │ 1011000250000             203      2018                 12
                                                              78 columns omitted

In [6]:
names(C)

82-element Vector{String}:
 "PIN"
 "Property Class"
 "Tax Year"
 "Neighborhood Code"
 "Land Square Feet"
 "Town Code"
 "Type of Residence"
 "Apartments"
 "Wall Material"
 "Roof Material"
 "Rooms"
 "Bedrooms"
 "Basement"
 ⋮
 "Lot Size Squared"
 "Improvement Size Squared"
 "Location Factor"
 "Garage indicator"
 "Residential share of building"
 "Pure Market Sale"
 "Pure Market Filter"
 "Neigborhood Code (mapping)"
 "Square root of lot size"
 "Square root of age"
 "Square root of improvement size"
 "Town and Neighborhood"

In [7]:
describe(C)

82×7 DataFrame
 Row │ variable                         mean        min            median      ⋯
     │ Symbol                           Union…      Any            Union…      ⋯
─────┼──────────────────────────────────────────────────────────────────────────
   1 │ PIN                              1.43324e13  1011000040000  1.40521e13  ⋯
   2 │ Property Class                   242.894     200            211.0
   3 │ Tax Year                         2018.79     2018           2019.0
   4 │ Neighborhood Code                92.1232     10             70.0
   5 │ Land Square Feet                 69733.1     0              7500.0      ⋯
   6 │ Town Code                        43.3362     10             35.0
   7 │ Type of Residence                2.10847     1              2.0
   8 │ Apartments                       0.332234    -5             0.0
   9 │ Wall Material                    1.96236     1              2.0         ⋯
  10 │ Roof Material                    1.15545     1              1.0
  11 │ Rooms                            7.0797      2              6.0
  ⋮  │                ⋮                     ⋮             ⋮            ⋮       ⋱
  73 │ Location Factor                  1.0         -0.858601      0.903182
  74 │ Garage indicator                 0.845017    0              1.0         ⋯
  75 │ Residential share of building    0.990788    0.0032         1.0
  76 │ Pure Market Sale                 0.0433686   0              0.0
  77 │ Pure Market Filter               0.0433686   0              0.0
  78 │ Neigborhood Code (mapping)       92.1232     10             70.0        ⋯
  79 │ Square root of lot size          155.045     0.0            86.6025
  80 │ Square root of age               7.26627     1.0            7.48331
  81 │ Square root of improvement size  41.7091     0.0            38.7943
  82 │ Town and Neighborhood            18945.4     1011           7171.0      ⋯
                                                   3 columns and 61 rows omitted

In [15]:
?dropdims

search: dropdims



```
dropdims(A; dims)
```

Return an array with the same data as `A`, but with the dimensions specified by `dims` removed. `size(A,d)` must equal 1 for every `d` in `dims`, and repeated dimensions or numbers outside `1:ndims(A)` are forbidden.

The result shares the same underlying data as `A`, such that the result is mutable if and only if `A` is mutable, and setting elements of one alters the values of the other.

See also: [`reshape`](@ref), [`vec`](@ref).

# Examples

```jldoctest
julia> a = reshape(Vector(1:4),(2,2,1,1))
2×2×1×1 Array{Int64, 4}:
[:, :, 1, 1] =
 1  3
 2  4

julia> b = dropdims(a; dims=3)
2×2×1 Array{Int64, 3}:
[:, :, 1] =
 1  3
 2  4

julia> b[1,1,1] = 5; a
2×2×1×1 Array{Int64, 4}:
[:, :, 1, 1] =
 5  3
 2  4
```


In [ ]:
eruptions = D[!,:Eruptions]
scatter(eruptions,label="eruptions")
waittime = D[!,:'Tax Year']
scatter!(waittime,label="Tax Year")